export interface SeedSource {
  source_type: string;
  source_name: string;
  source_url: string;
  scraper_config: Record<string, any>;
  detection_keywords: string[] | null;
  scrape_frequency_minutes: number;
}

export const SEED_SOURCES: SeedSource[] = [
  {
    source_type: "ayodonor",
    source_name: "AyoDonor PMI Nasional",
    source_url: "https://ayodonor.pmi.or.id",
    scraper_config: {},
    detection_keywords: null,
    scrape_frequency_minutes: 360,
  },
  {
    source_type: "pmi_national",
    source_name: "PMI Pusat",
    source_url: "https://pmi.or.id",
    scraper_config: {
      containerSelector: "article, .post, .berita-item",
      titleSelector: "h2, h3, .entry-title",
    },
    detection_keywords: null,
    scrape_frequency_minutes: 360,
  },
  {
    source_type: "pmi_province",
    source_name: "PMI Provinsi Aceh",
    source_url: "https://aceh.pmi.or.id",
    scraper_config: { containerSelector: "article, .post" },
    detection_keywords: null,
    scrape_frequency_minutes: 720,
  },
  {
    source_type: "pmi_province",
    source_name: "PMI Provinsi Sumatera Utara",
    source_url: "https://sumut.pmi.or.id",
    scraper_config: { containerSelector: "article, .post" },
    detection_keywords: null,
    scrape_frequency_minutes: 720,
  },
  {
    source_type: "pmi_province",
    source_name: "PMI Provinsi Sumatera Barat",
    source_url: "https://sumbar.pmi.or.id",
    scraper_config: { containerSelector: "article, .post" },
    detection_keywords: null,
    scrape_frequency_minutes: 720,
  },
  {
    source_type: "pmi_province",
    source_name: "PMI Provinsi Riau",
    source_url: "https://riau.pmi.or.id",
    scraper_config: { containerSelector: "article, .post" },
    detection_keywords: null,
    scrape_frequency_minutes: 720,
  },
  {
    source_type: "pmi_province",
    source_name: "PMI Provinsi Jambi",
    source_url: "https://jambi.pmi.or.id",
    scraper_config: { containerSelector: "article, .post" },
    detection_keywords: null,
    scrape_frequency_minutes: 720,
  },
  {
    source_type: "pmi_province",
    source_name: "PMI Provinsi Sumatera Selatan",
    source_url: "https://sumsel.pmi.or.id",
    scraper_config: { containerSelector: "article, .post" },
    detection_keywords: null,
    scrape_frequency_minutes: 720,
  },
  {
    source_type: "pmi_province",
    source_name: "PMI Provinsi Bengkulu",
    source_url: "https://bengkulu.pmi.or.id",
    scraper_config: { containerSelector: "article, .post" },
    detection_keywords: null,
    scrape_frequency_minutes: 720,
  },
  {
    source_type: "pmi_province",
    source_name: "PMI Provinsi Lampung",
    source_url: "https://lampung.pmi.or.id",
    scraper_config: { containerSelector: "article, .post" },
    detection_keywords: null,
    scrape_frequency_minutes: 720,
  },
  {
    source_type: "pmi_province",
    source_name: "PMI Provinsi Kepulauan Bangka Belitung",
    source_url: "https://babel.pmi.or.id",
    scraper_config: { containerSelector: "article, .post" },
    detection_keywords: null,
    scrape_frequency_minutes: 720,
  },
  {
    source_type: "pmi_province",
    source_name: "PMI Provinsi Kepulauan Riau",
    source_url: "https://kepri.pmi.or.id",
    scraper_config: { containerSelector: "article, .post" },
    detection_keywords: null,
    scrape_frequency_minutes: 720,
  },
  {
    source_type: "pmi_province",
    source_name: "PMI Provinsi DKI Jakarta",
    source_url: "https://jakarta.pmi.or.id",
    scraper_config: { containerSelector: "article, .post" },
    detection_keywords: null,
    scrape_frequency_minutes: 720,
  },
  {
    source_type: "pmi_province",
    source_name: "PMI Provinsi Jawa Barat",
    source_url: "https://jabar.pmi.or.id",
    scraper_config: { containerSelector: "article, .post" },
    detection_keywords: null,
    scrape_frequency_minutes: 720,
  },
  {
    source_type: "pmi_province",
    source_name: "PMI Provinsi Jawa Tengah",
    source_url: "https://jateng.pmi.or.id",
    scraper_config: { containerSelector: "article, .post" },
    detection_keywords: null,
    scrape_frequency_minutes: 720,
  },
  {
    source_type: "pmi_province",
    source_name: "PMI Provinsi DI Yogyakarta",
    source_url: "https://diy.pmi.or.id",
    scraper_config: { containerSelector: "article, .post" },
    detection_keywords: null,
    scrape_frequency_minutes: 720,
  },
  {
    source_type: "pmi_province",
    source_name: "PMI Provinsi Jawa Timur",
    source_url: "https://jatim.pmi.or.id",
    scraper_config: { containerSelector: "article, .post" },
    detection_keywords: null,
    scrape_frequency_minutes: 720,
  },
  {
    source_type: "pmi_province",
    source_name: "PMI Provinsi Banten",
    source_url: "https://banten.pmi.or.id",
    scraper_config: { containerSelector: "article, .post" },
    detection_keywords: null,
    scrape_frequency_minutes: 720,
  },
  {
    source_type: "pmi_province",
    source_name: "PMI Provinsi Bali",
    source_url: "https://bali.pmi.or.id",
    scraper_config: { containerSelector: "article, .post" },
    detection_keywords: null,
    scrape_frequency_minutes: 720,
  },
  {
    source_type: "pmi_province",
    source_name: "PMI Provinsi Nusa Tenggara Barat",
    source_url: "https://ntb.pmi.or.id",
    scraper_config: { containerSelector: "article, .post" },
    detection_keywords: null,
    scrape_frequency_minutes: 720,
  },
  {
    source_type: "pmi_province",
    source_name: "PMI Provinsi Nusa Tenggara Timur",
    source_url: "https://ntt.pmi.or.id",
    scraper_config: { containerSelector: "article, .post" },
    detection_keywords: null,
    scrape_frequency_minutes: 720,
  },
  {
    source_type: "pmi_province",
    source_name: "PMI Provinsi Kalimantan Barat",
    source_url: "https://kalbar.pmi.or.id",
    scraper_config: { containerSelector: "article, .post" },
    detection_keywords: null,
    scrape_frequency_minutes: 720,
  },
  {
    source_type: "pmi_province",
    source_name: "PMI Provinsi Kalimantan Tengah",
    source_url: "https://kalteng.pmi.or.id",
    scraper_config: { containerSelector: "article, .post" },
    detection_keywords: null,
    scrape_frequency_minutes: 720,
  },
  {
    source_type: "pmi_province",
    source_name: "PMI Provinsi Kalimantan Selatan",
    source_url: "https://kalsel.pmi.or.id",
    scraper_config: { containerSelector: "article, .post" },
    detection_keywords: null,
    scrape_frequency_minutes: 720,
  },
  {
    source_type: "pmi_province",
    source_name: "PMI Provinsi Kalimantan Timur",
    source_url: "https://kaltim.pmi.or.id",
    scraper_config: { containerSelector: "article, .post" },
    detection_keywords: null,
    scrape_frequency_minutes: 720,
  },
  {
    source_type: "pmi_province",
    source_name: "PMI Provinsi Kalimantan Utara",
    source_url: "https://kaltara.pmi.or.id",
    scraper_config: { containerSelector: "article, .post" },
    detection_keywords: null,
    scrape_frequency_minutes: 720,
  },
  {
    source_type: "pmi_province",
    source_name: "PMI Provinsi Sulawesi Utara",
    source_url: "https://sulut.pmi.or.id",
    scraper_config: { containerSelector: "article, .post" },
    detection_keywords: null,
    scrape_frequency_minutes: 720,
  },
  {
    source_type: "pmi_province",
    source_name: "PMI Provinsi Sulawesi Tengah",
    source_url: "https://sulteng.pmi.or.id",
    scraper_config: { containerSelector: "article, .post" },
    detection_keywords: null,
    scrape_frequency_minutes: 720,
  },
  {
    source_type: "pmi_province",
    source_name: "PMI Provinsi Sulawesi Selatan",
    source_url: "https://sulsel.pmi.or.id",
    scraper_config: { containerSelector: "article, .post" },
    detection_keywords: null,
    scrape_frequency_minutes: 720,
  },
  {
    source_type: "pmi_province",
    source_name: "PMI Provinsi Sulawesi Tenggara",
    source_url: "https://sultra.pmi.or.id",
    scraper_config: { containerSelector: "article, .post" },
    detection_keywords: null,
    scrape_frequency_minutes: 720,
  },
  {
    source_type: "pmi_province",
    source_name: "PMI Provinsi Gorontalo",
    source_url: "https://gorontalo.pmi.or.id",
    scraper_config: { containerSelector: "article, .post" },
    detection_keywords: null,
    scrape_frequency_minutes: 720,
  },
  {
    source_type: "pmi_province",
    source_name: "PMI Provinsi Sulawesi Barat",
    source_url: "https://sulbar.pmi.or.id",
    scraper_config: { containerSelector: "article, .post" },
    detection_keywords: null,
    scrape_frequency_minutes: 720,
  },
  {
    source_type: "pmi_province",
    source_name: "PMI Provinsi Maluku",
    source_url: "https://maluku.pmi.or.id",
    scraper_config: { containerSelector: "article, .post" },
    detection_keywords: null,
    scrape_frequency_minutes: 720,
  },
  {
    source_type: "pmi_province",
    source_name: "PMI Provinsi Maluku Utara",
    source_url: "https://malut.pmi.or.id",
    scraper_config: { containerSelector: "article, .post" },
    detection_keywords: null,
    scrape_frequency_minutes: 720,
  },
  {
    source_type: "pmi_province",
    source_name: "PMI Provinsi Papua",
    source_url: "https://papua.pmi.or.id",
    scraper_config: { containerSelector: "article, .post" },
    detection_keywords: null,
    scrape_frequency_minutes: 720,
  },
  {
    source_type: "pmi_province",
    source_name: "PMI Provinsi Papua Barat",
    source_url: "https://pabar.pmi.or.id",
    scraper_config: { containerSelector: "article, .post" },
    detection_keywords: null,
    scrape_frequency_minutes: 720,
  },
  {
    source_type: "pmi_province",
    source_name: "PMI Provinsi Papua Selatan",
    source_url: "https://papuaselatan.pmi.or.id",
    scraper_config: { containerSelector: "article, .post" },
    detection_keywords: null,
    scrape_frequency_minutes: 720,
  },
  {
    source_type: "pmi_province",
    source_name: "PMI Provinsi Papua Tengah",
    source_url: "https://papuaten.pmi.or.id",
    scraper_config: { containerSelector: "article, .post" },
    detection_keywords: null,
    scrape_frequency_minutes: 720,
  },
  {
    source_type: "pmi_province",
    source_name: "PMI Provinsi Papua Pegunungan",
    source_url: "https://papuapegunungan.pmi.or.id",
    scraper_config: { containerSelector: "article, .post" },
    detection_keywords: null,
    scrape_frequency_minutes: 720,
  },
  {
    source_type: "pmi_province",
    source_name: "PMI Provinsi Papua Barat Daya",
    source_url: "https://pabaraya.pmi.or.id",
    scraper_config: { containerSelector: "article, .post" },
    detection_keywords: null,
    scrape_frequency_minutes: 720,
  },
  {
    source_type: "pmi_city",
    source_name: "PMI Kota Bandung",
    source_url: "https://pmikotabandung.org",
    scraper_config: { containerSelector: "article, .berita-item, .post" },
    detection_keywords: null,
    scrape_frequency_minutes: 720,
  },
  {
    source_type: "pmi_city",
    source_name: "PMI Kota Batam",
    source_url: "https://updpmibatam.id",
    scraper_config: { containerSelector: "article, .post, .kegiatan-item" },
    detection_keywords: null,
    scrape_frequency_minutes: 720,
  },
  {
    source_type: "pmi_city",
    source_name: "PMI Bali (Jadwal Mobile)",
    source_url: "https://pmibali.online",
    scraper_config: { containerSelector: "table tr, .jadwal-item" },
    detection_keywords: null,
    scrape_frequency_minutes: 360,
  },
  {
    source_type: "pmi_city",
    source_name: "PMI Kota Tangerang Selatan",
    source_url: "https://uddpmitangsel.id",
    scraper_config: { containerSelector: "article, .post, .agenda-item" },
    detection_keywords: null,
    scrape_frequency_minutes: 720,
  },
  {
    source_type: "pmi_city",
    source_name: "PMI Kota Pontianak",
    source_url: "https://pmikotapontianak.or.id",
    scraper_config: { containerSelector: "article, .post, .berita" },
    detection_keywords: null,
    scrape_frequency_minutes: 720,
  },
  {
    source_type: "pmi_city",
    source_name: "PMI Kabupaten Malang",
    source_url: "https://www.pmikabmalang.or.id",
    scraper_config: { containerSelector: "article, .post, .berita-item" },
    detection_keywords: null,
    scrape_frequency_minutes: 720,
  },
  {
    source_type: "pmi_city",
    source_name: "PMI Kabupaten Bandung",
    source_url: "https://pmikabbandung.or.id",
    scraper_config: { containerSelector: "article, .post, .kegiatan" },
    detection_keywords: null,
    scrape_frequency_minutes: 720,
  },
  {
    source_type: "pmi_city",
    source_name: "PMI Kota Surabaya",
    source_url: "https://pmikotasurabaya.or.id",
    scraper_config: { containerSelector: "article, .post" },
    detection_keywords: null,
    scrape_frequency_minutes: 720,
  },
  {
    source_type: "pmi_city",
    source_name: "PMI Kota Medan",
    source_url: "https://pmikotamedan.or.id",
    scraper_config: { containerSelector: "article, .post" },
    detection_keywords: null,
    scrape_frequency_minutes: 720,
  },
  {
    source_type: "pmi_city",
    source_name: "PMI Kota Makassar",
    source_url: "https://pmikotamakassar.or.id",
    scraper_config: { containerSelector: "article, .post" },
    detection_keywords: null,
    scrape_frequency_minutes: 720,
  },
  {
    source_type: "pmi_city",
    source_name: "PMI Kota Semarang",
    source_url: "https://pmikotasemarang.or.id",
    scraper_config: { containerSelector: "article, .post" },
    detection_keywords: null,
    scrape_frequency_minutes: 720,
  },
  {
    source_type: "pmi_city",
    source_name: "PMI Kota Palembang",
    source_url: "https://pmikotapalembang.or.id",
    scraper_config: { containerSelector: "article, .post" },
    detection_keywords: null,
    scrape_frequency_minutes: 720,
  },
];
